import React from 'react';

// Voice Chat Hook
export const useVoiceChat = () => {
  const [recording, setRecording] = React.useState(false);
  const mediaRecorderRef = React.useRef(null);

  const startRecording = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ 
        audio: {
          echoCancellation: true,
          noiseSuppression: true,
          autoGainControl: true
        }
      });

      const mediaRecorder = new MediaRecorder(stream);
      mediaRecorderRef.current = mediaRecorder;
      const chunks = [];

      mediaRecorder.ondataavailable = (e) => chunks.push(e.data);
      
      mediaRecorder.onstop = () => {
        const blob = new Blob(chunks, { type: 'audio/wav' });
        return blob;
      };

      mediaRecorder.start();
      setRecording(true);
    } catch (error) {
      console.error('Microphone access denied:', error);
    }
  };

  const stopRecording = () => {
    if (mediaRecorderRef.current && recording) {
      mediaRecorderRef.current.stop();
      mediaRecorderRef.current.stream.getTracks().forEach(track => track.stop());
      setRecording(false);
    }
  };

  const synthesizeSpeech = async (text, rate = 1.0) => {
    if ('speechSynthesis' in window) {
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.rate = rate;
      speechSynthesis.speak(utterance);
    }
  };

  return {
    recording,
    startRecording,
    stopRecording,
    synthesizeSpeech
  };
};

// AI Response Hook
export const useAIResponse = () => {
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState(null);

  const generateResponse = async (messages) => {
    setLoading(true);
    setError(null);
    try {
      // This would integrate with your OpenAI API
      // For now, it's a placeholder
      return 'Response generated by AI';
    } catch (err) {
      setError(err.message);
      return null;
    } finally {
      setLoading(false);
    }
  };

  return { generateResponse, loading, error };
};

// File Upload Hook
export const useFileUpload = () => {
  const [uploading, setUploading] = React.useState(false);
  const [error, setError] = React.useState(null);

  const uploadFile = async (file, conversationId) => {
    setUploading(true);
    setError(null);
    try {
      const formData = new FormData();
      formData.append('file', file);
      formData.append('conversationId', conversationId);
      
      // Upload logic handled by API
      return { success: true };
    } catch (err) {
      setError(err.message);
      return { success: false };
    } finally {
      setUploading(false);
    }
  };

  return { uploadFile, uploading, error };
};
